package com.spring.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dctSchedual
 */
public class DctSchedual {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.patid
     *
     * @mbg.generated
     */
    private Integer patid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.dctcode
     *
     * @mbg.generated
     */
    private String dctcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.dctname
     *
     * @mbg.generated
     */
    private String dctname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.ghtime
     *
     * @mbg.generated
     */
    private String ghtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.hy
     *
     * @mbg.generated
     */
    private Integer hy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.zwname
     *
     * @mbg.generated
     */
    private String zwname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.idcard
     *
     * @mbg.generated
     */
    private String idcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.plane1
     *
     * @mbg.generated
     */
    private String plane1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.plane2
     *
     * @mbg.generated
     */
    private String plane2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.plane3
     *
     * @mbg.generated
     */
    private String plane3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.plane4
     *
     * @mbg.generated
     */
    private String plane4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dctSchedual.ghks
     *
     * @mbg.generated
     */
    private String ghks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.patid
     *
     * @return the value of dctSchedual.patid
     *
     * @mbg.generated
     */
    public Integer getPatid() {
        return patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.patid
     *
     * @param patid the value for dctSchedual.patid
     *
     * @mbg.generated
     */
    public void setPatid(Integer patid) {
        this.patid = patid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.dctcode
     *
     * @return the value of dctSchedual.dctcode
     *
     * @mbg.generated
     */
    public String getDctcode() {
        return dctcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.dctcode
     *
     * @param dctcode the value for dctSchedual.dctcode
     *
     * @mbg.generated
     */
    public void setDctcode(String dctcode) {
        this.dctcode = dctcode == null ? null : dctcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.dctname
     *
     * @return the value of dctSchedual.dctname
     *
     * @mbg.generated
     */
    public String getDctname() {
        return dctname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.dctname
     *
     * @param dctname the value for dctSchedual.dctname
     *
     * @mbg.generated
     */
    public void setDctname(String dctname) {
        this.dctname = dctname == null ? null : dctname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.ghtime
     *
     * @return the value of dctSchedual.ghtime
     *
     * @mbg.generated
     */
    public String getGhtime() {
        return ghtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.ghtime
     *
     * @param ghtime the value for dctSchedual.ghtime
     *
     * @mbg.generated
     */
    public void setGhtime(String ghtime) {
        this.ghtime = ghtime == null ? null : ghtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.hy
     *
     * @return the value of dctSchedual.hy
     *
     * @mbg.generated
     */
    public Integer getHy() {
        return hy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.hy
     *
     * @param hy the value for dctSchedual.hy
     *
     * @mbg.generated
     */
    public void setHy(Integer hy) {
        this.hy = hy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.zwname
     *
     * @return the value of dctSchedual.zwname
     *
     * @mbg.generated
     */
    public String getZwname() {
        return zwname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.zwname
     *
     * @param zwname the value for dctSchedual.zwname
     *
     * @mbg.generated
     */
    public void setZwname(String zwname) {
        this.zwname = zwname == null ? null : zwname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.idcard
     *
     * @return the value of dctSchedual.idcard
     *
     * @mbg.generated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.idcard
     *
     * @param idcard the value for dctSchedual.idcard
     *
     * @mbg.generated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.plane1
     *
     * @return the value of dctSchedual.plane1
     *
     * @mbg.generated
     */
    public String getPlane1() {
        return plane1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.plane1
     *
     * @param plane1 the value for dctSchedual.plane1
     *
     * @mbg.generated
     */
    public void setPlane1(String plane1) {
        this.plane1 = plane1 == null ? null : plane1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.plane2
     *
     * @return the value of dctSchedual.plane2
     *
     * @mbg.generated
     */
    public String getPlane2() {
        return plane2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.plane2
     *
     * @param plane2 the value for dctSchedual.plane2
     *
     * @mbg.generated
     */
    public void setPlane2(String plane2) {
        this.plane2 = plane2 == null ? null : plane2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.plane3
     *
     * @return the value of dctSchedual.plane3
     *
     * @mbg.generated
     */
    public String getPlane3() {
        return plane3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.plane3
     *
     * @param plane3 the value for dctSchedual.plane3
     *
     * @mbg.generated
     */
    public void setPlane3(String plane3) {
        this.plane3 = plane3 == null ? null : plane3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.plane4
     *
     * @return the value of dctSchedual.plane4
     *
     * @mbg.generated
     */
    public String getPlane4() {
        return plane4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.plane4
     *
     * @param plane4 the value for dctSchedual.plane4
     *
     * @mbg.generated
     */
    public void setPlane4(String plane4) {
        this.plane4 = plane4 == null ? null : plane4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dctSchedual.ghks
     *
     * @return the value of dctSchedual.ghks
     *
     * @mbg.generated
     */
    public String getGhks() {
        return ghks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dctSchedual.ghks
     *
     * @param ghks the value for dctSchedual.ghks
     *
     * @mbg.generated
     */
    public void setGhks(String ghks) {
        this.ghks = ghks == null ? null : ghks.trim();
    }
}